### PR TITLE
ci: separate build from pypi deploy, store build artifacts

### PR DESCRIPTION
**Pull request by phw**

### CODE REVIEW

**Comment by phw** [comment]
Build running at https://github.com/phw/nmslib-metabrainz/actions/runs/7819078083

**Comment by phw** [comment]
@mayhem Please check. This should work for Windows and Linux. macOS build is for now disabled.

The most important parts are:

- Build and PyPI deploy are separated. The pypa/gh-action-pypi-publish action does not run on Windows. So it's better to build the wheels first on separate OS images then deploy all in one step
- The above has the positive side effect that built wheels are available as artifacts, independent whether deployment is triggered or not
- had to deactive 32 bit builds on windows, python 3.6 to 3.8 build and all pypy builds
- macOS does not yet build


https://github.com/phw/nmslib-metabrainz/actions/runs/7819956824

**Review by mayhem — APPROVED** [review]
Looks much better than my version!

**Comment by mayhem** [comment]
Thanks!

**Pull request merged**
